name: todo-infra
on: workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs:
  test:
    runs-on: [self-hosted, kirti]
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Terraform Installation
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Terraform Init
        id: init
        shell: cmd
        working-directory: todoapp_infra
        run: terraform init -input=false
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Terraform fmt
        id: fmt
        shell: cmd
        working-directory: todoapp_infra
        run: terraform fmt 
        continue-on-error: true
      - name: Terraform Validate
        id: validate
        shell: cmd
        working-directory: todoapp_infra
        run: terraform validate 
      - name: Terraform Plan
        id: plan
        working-directory: todoapp_infra
        shell: cmd
        run: |
          echo Running terraform plan...
          terraform.exe plan -no-color > plan.txt
          type plan.txt
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     
      

   
    

