name: todo-infra
on: workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs:
  test:
    runs-on: [self-hosted, kirti]
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: "54e2be3b-84f1-4e30-8071-9ad1c0cf93a1"
          tenant-id: "25da0254-8640-4e13-9016-d3428661a477"
          subscription-id: "972b29e5-b4b2-4f43-b814-02879737840d"
      # - name: Azure CLI script
      #   uses: azure/cli@v2
      #   with:
      #     azcliversion: latest
      #     inlineScript: |
      #       az account show

   
    

